### PR TITLE
changed favicon

### PR DESCRIPTION
**Pull request by tamago01**
Could you please review it?
It is hosted here: https://lets-code-two.vercel.app/

### CODE REVIEW

**Comment by tamago01** [comment]
@karantec how do I know if my PR was accepted or not??

**Comment by tamago01** [comment]
@karantec could you please review my PR? This is my first ever PR.

**Comment by karantec** [comment]
Ya sure

**Comment by karantec** [comment]
Ya sure

**Comment by tamago01** [comment]
@karantec hello karan, if my work was satisfactory, could you please accept and close my PR? :D And also, add hacktober label please.

**Comment by karantec** [comment]
Ya let me see after my office work

**Pull request closed without merging**
